package stream

// fieldNames maps each streaming Service to the ordered list of human-readable
// field names for indices 0..N-1. The Schwab streamer returns data keyed by
// stringified numeric indices ("0", "1", ...); this table lets callers map
// those indices back to human-readable names. The API accepts either the
// numeric indices or the field names in subscription "fields" parameters.
//
// The tables here match Schwabdev's translate.py with the corrected CHART_EQUITY
// ordering documented in spec Appendix C#1.
//
// Services for which we do not ship a field table return a nil slice from
// FieldNames; callers can still subscribe by numeric index in that case.
var fieldNames = map[Service][]string{
	LevelOneEquities: {
		"Symbol",
		"Bid Price",
		"Ask Price",
		"Last Price",
		"Bid Size",
		"Ask Size",
		"Ask ID",
		"Bid ID",
		"Total Volume",
		"Last Size",
		"High Price",
		"Low Price",
		"Close Price",
		"Exchange ID",
		"Marginable",
		"Description",
		"Last ID",
		"Open Price",
		"Net Change",
		"52 Week High",
		"52 Week Low",
		"PE Ratio",
		"Annual Dividend Amount",
		"Dividend Yield",
		"NAV",
		"Exchange Name",
		"Dividend Date",
		"Regular Market Quote",
		"Regular Market Trade",
		"Regular Market Last Price",
		"Regular Market Last Size",
		"Regular Market Net Change",
		"Security Status",
		"Mark Price",
		"Quote Time in Long",
		"Trade Time in Long",
		"Regular Market Trade Time in Long",
		"Bid Time",
		"Ask Time",
		"Ask MIC ID",
		"Bid MIC ID",
		"Last MIC ID",
		"Net Percent Change",
		"Regular Market Percent Change",
		"Mark Price Net Change",
		"Mark Price Percent Change",
		"Hard to Borrow Quantity",
		"Hard To Borrow Rate",
		"Hard to Borrow",
		"Shortable",
		"Post-Market Net Change",
		"Post-Market Percent Change",
	},
	LevelOneOptions: {
		"Symbol",
		"Description",
		"Bid Price",
		"Ask Price",
		"Last Price",
		"High Price",
		"Low Price",
		"Close Price",
		"Total Volume",
		"Open Interest",
		"Volatility",
		"Money Intrinsic Value",
		"Expiration Year",
		"Multiplier",
		"Digits",
		"Open Price",
		"Bid Size",
		"Ask Size",
		"Last Size",
		"Net Change",
		"Strike Price",
		"Contract Type",
		"Underlying",
		"Expiration Month",
		"Deliverables",
		"Time Value",
		"Expiration Day",
		"Days to Expiration",
		"Delta",
		"Gamma",
		"Theta",
		"Vega",
		"Rho",
		"Security Status",
		"Theoretical Option Value",
		"Underlying Price",
		"UV Expiration Type",
		"Mark Price",
		"Quote Time in Long",
		"Trade Time in Long",
		"Exchange ID",
		"Exchange Name",
		"Last Trading Day",
		"Settlement Type",
		"Net Percent Change",
		"Mark Price Net Change",
		"Mark Price Percent Change",
		"Implied Yield",
		"Is Penny",
		"Option Root",
		"52 Week High",
		"52 Week Low",
		"Indicative Asking Price",
		"Indicative Bid Price",
		"Indicative Quote Time",
		"Exercise Type",
	},
	LevelOneFutures: {
		"Symbol",
		"Bid Price",
		"Ask Price",
		"Last Price",
		"Bid Size",
		"Ask Size",
		"Bid ID",
		"Ask ID",
		"Total Volume",
		"Last Size",
		"Quote Time",
		"Trade Time",
		"High Price",
		"Low Price",
		"Close Price",
		"Exchange ID",
		"Description",
		"Last ID",
		"Open Price",
		"Net Change",
		"Future Percent Change",
		"Exchange Name",
		"Security Status",
		"Open Interest",
		"Mark",
		"Tick",
		"Tick Amount",
		"Product",
		"Future Price Format",
		"Future Trading Hours",
		"Future Is Tradable",
		"Future Multiplier",
		"Future Is Active",
		"Future Settlement Price",
		"Future Active Symbol",
		"Future Expiration Date",
		"Expiration Style",
		"Ask Time",
		"Bid Time",
		"Quoted in Session",
		"Settlement Date",
	},
	LevelOneFuturesOptions: {
		"Symbol",
		"Bid Price",
		"Ask Price",
		"Last Price",
		"Bid Size",
		"Ask Size",
		"Bid ID",
		"Ask ID",
		"Total Volume",
		"Last Size",
		"Quote Time",
		"Trade Time",
		"High Price",
		"Low Price",
		"Close Price",
		"Last ID",
		"Description",
		"Open Price",
		"Open Interest",
		"Mark",
		"Tick",
		"Tick Amount",
		"Future Multiplier",
		"Future Settlement Price",
		"Underlying Symbol",
		"Strike Price",
		"Future Expiration Date",
		"Expiration Style",
		"Contract Type",
		"Security Status",
		"Exchange ID",
		"Exchange Name",
	},
	LevelOneForex: {
		"Symbol",
		"Bid Price",
		"Ask Price",
		"Last Price",
		"Bid Size",
		"Ask Size",
		"Total Volume",
		"Last Size",
		"Quote Time",
		"Trade Time",
		"High Price",
		"Low Price",
		"Close Price",
		"Exchange ID",
		"Description",
		"Open Price",
		"Net Change",
		"Percent Change",
		"Exchange Name",
		"Digits",
		"Security Status",
		"Tick",
		"Tick Amount",
		"Product",
		"Trading Hours",
		"Is Tradable",
		"Market Maker",
		"52 Week High",
		"52 Week Low",
		"Mark",
	},
	NYSEBook: {
		"Symbol",
		"Market Snapshot Time",
		"Bid Book",
		"Ask Book",
	},
	NasdaqBook: {
		"Symbol",
		"Market Snapshot Time",
		"Bid Book",
		"Ask Book",
	},
	OptionsBook: {
		"Symbol",
		"Market Snapshot Time",
		"Bid Book",
		"Ask Book",
	},
	// CHART_EQUITY ordering corrected per spec Appendix C#1.
	ChartEquity: {
		"key",
		"Sequence",
		"Open Price",
		"High Price",
		"Low Price",
		"Close Price",
		"Volume",
		"Chart Time",
		"Chart Day",
	},
	ChartFutures: {
		"key",
		"Chart Time",
		"Open Price",
		"High Price",
		"Low Price",
		"Close Price",
		"Volume",
	},
	ScreenerEquity: {
		"Symbol",
		"Timestamp",
		"Sort Field",
		"Frequency",
		"Items",
	},
	ScreenerOption: {
		"Symbol",
		"Timestamp",
		"Sort Field",
		"Frequency",
		"Items",
	},
	AccountActivity: {
		"Subscription Key",
		"Account",
		"Message Type",
		"Message Data",
	},
}

// FieldNames returns the ordered list of human-readable field names for the
// given streaming service. Index i in the returned slice corresponds to wire
// key "i" in Schwab data frames.
//
// Returns nil if the service is not in the table. Callers may always
// subscribe by numeric index ("0,1,3") regardless of whether a field table
// is known.
//
// The returned slice is a defensive copy; callers may mutate it freely.
func FieldNames(s Service) []string {
	src, ok := fieldNames[s]
	if !ok {
		return nil
	}
	out := make([]string, len(src))
	copy(out, src)
	return out
}
